CONFIGURATION_M_3D_PMRNN = {
    "BATCH_SIZE": 16,
    "LEARNING_RATE": 1e-3,
    "OPTIMIZER": 'Adam',
    "N_EPOCHS": 2,
    "N_FILTERS": 5,
    "INPUT_SHAPE": (256, 256, 1),
    "LATENT_SPACE_DIM": 64,
    "REDUCED_DIMENSION": 256,
}

CONFIGURATION_ViT = {
    "BATCH_SIZE": 8,
    "LEARNING_RATE": 1e-3,
    "OPTIMIZER":'Adam',
    "PATCH_SIZE":16,
    "N_EPOCHS": 2,
    "N_FILTERS": 5,
    "INPUT_SHAPE":(256,256,1),
    "LATENT_SPACE_DIM" : 64,
    "REDUCED_DIMENSION" : 256,
    "N_HEADS" : 3,
    "HIDDEN_SIZE" : 256,
    "N_PATCHES" : 256,
    "N_LAYERS" : 1,
}


CONFIGURATION_3D_PMRNN = {
    "BATCH_SIZE": 8,
    "LEARNING_RATE": 0.001,
    "OPTIMIZER":'Adam',
    "N_EPOCHS": 10,
    "N_FILTERS": 6,
    "INPUT_SHAPE":(256,256,1),
    "LATENT_SPACE_DIM" : 64,
    "REDUCED_DIMENSION" : 128,
}